# 设备标识
MN: 010000A8900016F000169DC0
 # 系统编码
ST: 21
# 密码
PW: 888888 
# 上位机地址(若json配置文件为空,则用该地址)
SerAddress: 58.215.28.118:8901 
# 上报超时时间(秒）
OverTime: 5 
# 重发次数
ReCount: 3
# 实时数据上报间隔(秒)
RtdInterval: 30
# 心跳间隔,0为无心跳(秒)
KeepAlive: 0
# 心跳超时(秒）
PingTimeout: 15
# 分钟数据间隔
#MinInterval: 10
# 默认采样起始时间
#CstartTime: 000000
# 采样间隔时间(秒)
#CTime: 7200
# 出样时间间隔(秒)
#Stime: 240
# 因子代码(格式为:名称-代码)
# 存储间隔(秒)
StoreInterval: 60

Modbus:
    KeyCode:
        - 油烟-006
        - 颗粒物-a34004
        - TVOC-a24088
        - 温度-007
        - 湿度-008
        - 气压-a01006
        - 风机电流-012
        - 风机状态-011
        - 净化器电流-012
        - 净化器状态-011
    rule:
        # 每个参数的值长度(byte)
        vlength: 4
        # modbus值类型
        vtype: int32
        # 实际值=*multiply
        multiply: 0.01

